server:
  port: 8082
fileServer:
  url: http://192.168.5.32

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  dubbo:
    application: manage-web
    registry:
      protocol: zookeeper
      address: 192.168.5.32:2181
    protocol: dubbo
    base-package: com.lxj.gmall0419
    consumer:
      timeout: 10000
      check: false